services:
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend/db/:/var/lib/postgresql/17/docker

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    environment:
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend/:/src/
